openapi: 3.0.3
info:
  title: EazyShop Products APIs Definition
  description: |
     Using this OpenAPI specification, any consumer can understand the APIs that are exposed by EazyShop
  termsOfService: https://eazyshop.com/terms/
  contact:
    name: API Support
    url: https://www.eazyshop.com/support
    email: support@eazyshop.com
  license:
    name: EazyShop License
    url: https://www.eazyshop.com/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
  - url: https://development.eazyshop-server.com/v1
    description: Development server
paths:
  /categories:
    get:
      summary: List all catgories
      description: Returns the list of categories supported by EazyShop
      parameters:
        - name: categoryId
          in: query
          schema:
            type: integer
            minimum: 100
            maximum: 1000
          example: 101
      responses:
        '200':
          description: A list of catgories
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    categoryId:
                      type: integer
                    name:
                      type: string